# version: '3.1'
version: '2'
# Assignment: Writing a Compose File

# > Goal: Create a compose config for a local Drupal CMS website
# 
# - This empty directory is where you should create a docker-compose.yml 
# - Use the `drupal` image along with the `postgres` image
# - Set the version to 2
# - Use `ports` to expose Drupal on 8080
# - Be sure to setup POSTGRES_PASSWORD on postgres image
# - Walk though Drupal config in browser at http://localhost:8080
# - Tip: Drupal assumes DB is localhost, but it will actually be on the compose
# service name you give it
# - Use Docker Hub documentation to figure out the right environment and volume
# settings
# - Extra Credit: Use volumes to store Drupal unique data

services:
  web:
    image: drupal:8.2
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes 
    ports:
      - '8080:80'
  db:
    image: postgres:9.6
    environment:
      # - POSTGRES_DB=db
      # - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    
volumes:
  psql_data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
