# Task
#
# - Database upgrade with containers
# - Create postrgresql with named volume psql-data using version 9.6.1
# - Use Docker Hub to learn VOLUME path
# - Check logs, stop container
# - Create new container with postgresql with save named vol. version 9.6.2 
# - Check logs and validate

FROM postgres:9.6.1

VOLUME psql-data:/var/lib/postgresql/data


