# ***********************************************
# *  72. Assignment: Create Stack with Secrets  *
# ***********************************************
version: "3.1"
services:
  web:
    image: drupal:8.8
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes 
    ports:
      - '8080:80'
  postgres:
    image: postgres:10.11
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pwd
      - POSTGRES_USER=psql
      - POSTGRES_DATABASE=psql
    secrets:
      - psql_pwd
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql_pwd:
    external: true
